# Configuration for the DRP API Adapter

# Port for the GraphQL service to listen on.
port = 9091

# URL of the external DRP API.
# If not provided, it will fall back to the CHOREO_MOCK_DRP_CONNECTION_SERVICEURL environment variable.
serviceURL = "http://localhost:9090"

# API Key for authenticating with the external DRP API.
# If not provided, it will fall back to the CHOREO_MOCK_DRP_CONNECTION_APIKEY environment variable.
choreoApiKey = "your-api-key"